assortment/urls.py
from django.urls import path
from . import views
from . import rest_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.IndexPageView.as_view(), name='index'),
    path('motorcycle/<int:pk>/', views.AboutMotoView.as_view(), name='about_moto'),
    path('motorcycles/', views.MotorcyclesListView.as_view(), name='motorcycles_list'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('add_moto/', views.AddMotorcycleView.as_view(), name='add_moto_view'),
    path('add_user/', views.AddUserView.as_view(), name='add_user_view'),
    path('add_feature/<int:pk>/', views.AddFeatureView.as_view(), name='add_feature_view'),
    path('remove_feature/<int:pk>/', views.RemoveFeatureView.as_view(), name='remove_feature_view'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('add_model/', views.AddModelView.as_view(), name='add_model_view'),
    path('add_manufacturer/', views.AddManufacturerView.as_view(), name='add_manufacturer_view'),
    path('edit_moto/<int:pk>/', views.EditMotorcycleView.as_view(), name='edit_moto_view'),
    path('delete_moto/<int:pk>/', views.DeleteMotorcycleView.as_view(), name='delete_moto_view'),

    path('api/models/<int:manufacturer_id>', rest_views.get_models, name='get_all_models'),
    path('api/manufacturers', rest_views.get_manufacturers, name='get_all_manufacturers'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

motodatabase/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('assortment.urls')),
    path('admin/', admin.site.urls),

]

assortment/models.py
from django.db import models


class Manufacturer(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Model(models.Model):
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.manufacturer.name + " " + self.name


class Motorcycle(models.Model):
    name = models.CharField(max_length=50)
    model = models.ForeignKey(Model, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('Date published', auto_now_add=True)
    pub_user = models.ForeignKey('auth.User', related_name="publisher", on_delete=models.CASCADE)
    year = models.IntegerField(default=0)
    mileage = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    description = models.TextField(default='')
    show_to = models.ManyToManyField('auth.User', related_name="show_to", blank=True)

    def __str__(self):
        return str(self.name) + "(" + str(self.model) + ")"


class MotorcycleFeature(models.Model):
    motorcycle = models.ForeignKey(Motorcycle, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    description = models.TextField(default='')

    def __str__(self):
        return self.description

assortment/forms.py
from django import forms
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError

from assortment.models import Manufacturer


class LoginForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)  # TODO: разобраться, что за хрень
        super().__init__(*args, **kwargs)

    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def get_user(self):  # TODO: добавить логин по e-mail
        user = User.objects.filter(username=self.clean_username()).first()
        return user

    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username).first()
        if not user:
            raise ValidationError('Пользователя с таким логином не существует.')
        return username

    def clean_password(self):
        password = self.cleaned_data['password']
        if 'username' in self.cleaned_data:
            user = self.get_user()
            if not user.check_password(password):
                raise ValidationError('Неправильный пароль.')
        return password

    @property
    def field_order(self):
        return ['username', 'password']


class AddManufacturerForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('instance', None)  # TODO: разобраться, что за хрень
        super().__init__(*args, **kwargs)

    def clean_name(self):
        name = self.cleaned_data['name']
        if Manufacturer.objects.filter(name=name).first():
            raise ValidationError(name + ' был добавлен ранее.')
        return name

    def save(self):
        manufacturer = Manufacturer.objects.create(name=self.cleaned_data['name'])
        return manufacturer


class AddUserForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('instance', None)  # TODO: разобраться, что за хрень
        super().__init__(*args, **kwargs)

    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    email = forms.EmailField(label='Email', max_length=100)
    first_name = forms.CharField(label='First name', max_length=100)
    last_name = forms.CharField(label='Last name', max_length=100)
    is_staff = forms.BooleanField(label='Is staff', required=False)

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).first():
            raise ValidationError('Пользователя с таким логином уже существует.')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).first():
            raise ValidationError('Пользователя с таким e-mail уже существует.')
        return email

    def clean_password(self):
        password = self.cleaned_data['password']
        if validate_password(password):
            raise ValidationError('Пароль не удовлетворяет требованиям.')
        return password

    def save(self):
        user = User.objects.create_user(
            username=self.cleaned_data['username'],
            email=self.cleaned_data['email'],
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            is_staff=self.cleaned_data['is_staff'],)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user

assortment/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .forms import *
from .models import *

from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin

LoginRequiredMixin.login_url = '/login/'


class IndexPageView(generic.TemplateView):
    template_name = 'assortment/index.html'


def mock(request):
    return HttpResponse("Just empty page. Fuck off!")


class AboutMotoView(LoginRequiredMixin, generic.DetailView):
    model = Motorcycle
    template_name = 'assortment/about_motorcycle.html'


class MotorcyclesListView(LoginRequiredMixin, generic.ListView):
    template_name = 'assortment/motorcycle_list.html'
    context_object_name = 'motorcycle_list'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            if self.request.user.is_superuser:
                return Motorcycle.objects.all()
            return Motorcycle.objects.all().order_by('-pub_date').filter(show_to__in=[self.request.user])
        return None


class LoginView(auth_views.LoginView):
    template_name = 'assortment/login.html'
    form_class = LoginForm


class LogoutView(auth_views.LogoutView):
    template_name = 'assortment/logout.html'


class AddMotorcycleView(LoginRequiredMixin, generic.CreateView):
    model = Motorcycle
    template_name = 'assortment/add_motorcycle.html'
    fields = ['name', 'year', 'description', 'photo', 'show_to', 'price', 'mileage', 'model']

    manufacturers = Manufacturer.objects.all()

    def form_valid(self, form):
        form.instance.pub_user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('motorcycles_list')


class EditMotorcycleView(LoginRequiredMixin, generic.UpdateView):
    model = Motorcycle
    template_name = 'assortment/universal_form.html'  # TODO: переписать на изменение мотоцикла
    fields = ['name', 'year', 'description', 'photo', 'show_to', 'price', 'mileage', 'model']

    def dispatch(self, request, *args, **kwargs):
        if request.user != Motorcycle.objects.get(pk=kwargs['pk']).pub_user and not request.user.is_superuser:
            return HttpResponseRedirect(reverse('motorcycles_list'))
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("about_moto", kwargs={'pk': self.kwargs['pk']})


class DeleteMotorcycleView(LoginRequiredMixin, generic.DeleteView):
    model = Motorcycle
    template_name = 'assortment/delete_confirm.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user != Motorcycle.objects.get(pk=kwargs['pk']).pub_user and not request.user.is_superuser:
            return HttpResponseRedirect(reverse('motorcycles_list'))
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('motorcycles_list')


class AddUserView(LoginRequiredMixin, generic.CreateView):
    model = User
    template_name = 'assortment/add_user.html'
    form_class = AddUserForm
    # fields = ['username', 'password', 'email', 'first_name', 'last_name', 'is_staff']

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_superuser:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseRedirect(reverse('index'))

    def get_success_url(self):
        return reverse('motorcycles_list')  # TODO: добавить проверку формы на валидность


class AddFeatureView(LoginRequiredMixin, generic.CreateView):
    model = MotorcycleFeature
    template_name = 'assortment/add_feature.html'
    fields = ['photo', 'description']

    def dispatch(self, request, *args, **kwargs):
        if request.user != Motorcycle.objects.get(pk=kwargs['pk']).pub_user and not request.user.is_superuser:
            return HttpResponseRedirect(reverse('motorcycles_list'))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.motorcycle = Motorcycle.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("about_moto", kwargs={'pk': self.kwargs['pk']})


class RemoveFeatureView(LoginRequiredMixin, generic.DeleteView):
    model = MotorcycleFeature
    template_name = 'assortment/delete_confirm.html'
    motorcycle = None

    def dispatch(self, request, *args, **kwargs):
        self.motorcycle = MotorcycleFeature.objects.get(pk=kwargs['pk']).motorcycle
        if request.user != MotorcycleFeature.objects.get(
                pk=kwargs['pk']).motorcycle.pub_user and not request.user.is_superuser:
            return HttpResponseRedirect(reverse('motorcycles_list'))
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("about_moto", kwargs={'pk': self.motorcycle.pk})


class AddManufacturerView(LoginRequiredMixin, generic.CreateView):
    model = Manufacturer
    template_name = 'assortment/add_manufacturer.html'
    form_class = AddManufacturerForm

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff and not request.user.is_superuser:
            return HttpResponseRedirect(reverse('motorcycles_list'))
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('motorcycles_list')


class AddModelView(LoginRequiredMixin, generic.CreateView):
    model = Model
    template_name = 'assortment/add_model.html'
    fields = ['manufacturer', 'name']

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff and not request.user.is_superuser:
            return HttpResponseRedirect(reverse('motorcycles_list'))
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('motorcycles_list')

templates/assortment/about_motorcycle.html
{% extends 'assortment/base.html' %}
{% block content %}
{%if user in motorcycle.show_to.all or user.is_superuser %}
<h1>{{ motorcycle.model }} : {{ motorcycle.name }}
  {% if motorcycle.pub_user == user or user.is_superuser %}
  <a href="/edit_moto/{{ motorcycle.id }}/" class="btn btn-primary mb-2">Изменить</a>
  <a href="/delete_moto/{{ motorcycle.id }}/" class="btn btn-danger mb-2">Удалить</a>
  {% endif %}
</h1>
<div class="row">
  <div class="col-md-5 col-sm-7">
    {% if motorcycle.photo %}
    <img src="{{ motorcycle.photo.url }}" width="100%" class="featurette-image center-block img-responsive">
    {% endif %}
  </div>
  <div class="col-md-7 col-sm-5">
    <p>Год выпуска: {{ motorcycle.year }}</p>
    <p>Пробег: {{ motorcycle.mileage }} км</p>
    <p>Цена: {{ motorcycle.price }} руб</p>
    <p>Добавил {{ motorcycle.pub_user }} {{ motorcycle.pub_date|date:"d.m.Y" }}</p>
    <p id="mot_description">Описание: {{ motorcycle.description }}</p>
  </div>
</div>

<h2>Подробности:</h2>
<ul class="list-group">
  {% for feature in motorcycle.motorcyclefeature_set.all %}
  <li class="list-group-item">
    <div class="row">
      <div class="col-md-3">
        {% if feature.photo %}
        <img
            width="100%"
            src="{{ feature.photo.url }}"/>
        {% endif %}
      </div>
      <div class="col-md-9">
        <p>{{ feature.description }}</p>
        {% if motorcycle.pub_user == user or user.is_superuser %}
        <a href="/remove_feature/{{ feature.id }}/" class="btn btn-sm btn-danger">Удалить</a>
        {% endif %}
      </div>
    </div>
  </li>
  {% endfor %}
  {% if motorcycle.pub_user == user or user.is_superuser %}
  <li class="list-group-item">
    <a href="/add_feature/{{ motorcycle.id }}" class="btn btn-sm btn-success btn-block">Добавить</a>
  </li>
</ul>
{% endif %}
{% else %}
<h1>Доступ запрещен</h1>
{% endif %}
{% endblock %}

templates/assortment/add_feature.html
{% extends 'assortment/base.html' %}
{% block content %}
<style>
.form-add-feature {
  max-width: 600px;
  padding: 15px;
  margin: 0 auto;
}
</style>
<form class="form-add-feature" enctype="multipart/form-data" method="post">
  {% csrf_token %}
  <div class="input-group mb-1">
    <label for="id_photo">Фото:</label>
    <input class="form-control-file" type="file" name="photo" accept="image/*" id="id_photo">
  </div>
  <div class="input-group mb-1">
    <div class="input-group-prepend">
      <span class="input-group-text mb-1">Описание:</span>
    </div>
    <textarea class="form-control mb-1" name="description" cols="40" rows="10" required id="id_description"
              aria-label="Описание"></textarea>
  </div>
  <input class="btn btn-primary btn-block" type="submit" value="Добавить">
</form>
{% endblock %}

templates/assortment/add_manufacturer.html
{% extends 'assortment/base.html' %}
{% block content %}
<style>
.form-add-manufacturer {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
</style>
<form class="form-add-manufacturer" enctype="multipart/form-data" method="post">
  {% csrf_token %}
  <input class="form-control mb-1 {% if form.name.errors %} is-invalid {% endif %}" type="text" name="name" maxlength="30" required id="id_name"
         placeholder="Название">
  <div class="invalid-feedback">
      {% for error in form.name.errors %}
      <p>{{ error }}</p>
      {% endfor %}
    </div>
  <input class="btn btn-primary btn-block" type="submit" value="Добавить">
</form>
{% endblock %}

templates/assortment/add_model.html
{% extends 'assortment/base.html' %}
{% block content %}
<style>
.form-add-model {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
</style>
<form class="form-add-model" enctype="multipart/form-data" method="post">
  {% csrf_token %}

  <select class="custom-select" name="manufacturer" required id="id_manufacturer">
  <option value="" selected>Производитель</option>

  {% for manufacturer in form.manufacturer.field.queryset %}
    <option value="{{ manufacturer.id }}">{{ manufacturer.name }}</option>
  {% endfor %}
  </select>

  <input class="form-control mb-1" type="text" name="name" maxlength="50" required id="id_name"
         placeholder="Название">
  <input class="btn btn-primary btn-block" type="submit" value="Добавить">
</form>
{% endblock %}

templates/assortment/add_motorcycle.html
{% extends 'assortment/base.html' %}
{% block content %}
<style>
.form-add-motorcycle {
  max-width: 600px;
  padding: 15px;
  margin: 0 auto;
}




</style>
<form class="form-add-motorcycle" enctype="multipart/form-data" method="post">
  {% csrf_token %}

  <input class="form-control mb-1" type="text" name="name" maxlength="50" required id="id_name" placeholder="Имя">

  <select class="form-control mb-1" name="model" required id="select_manufacturer">
    <option value="" disabled selected hidden>Производитель</option>
  </select>


  <select class="form-control mb-1" name="model" required id="id_model">
    <option value="" disabled selected hidden>Модель</option>
  </select>

  <div class="input-group mb-2">
    <label for="id_photo">Фото:</label>
    <input class="form-control-file" type="file" name="photo" accept="image/*" id="id_photo">
  </div>

  <div class="input-group mb-1">
    <label class="input-group-text col-2" width="240" for="id_year">Год:</label>
    <input class="form-control col-10" type="number" name="year" value="2000" required id="id_year" placeholder="Год">
  </div>

  <div class="input-group mb-1">
    <label class="input-group-text col-2" for="id_price">Цена:</label>
    <input class="form-control col-10" type="number" name="price" value="0" required id="id_price">
  </div>

  <div class="input-group mb-1">
    <label class="input-group-text col-2" for="id_mileage">Пробег:</label>
    <input class="form-control col-10" type="number" name="mileage" value="0" required id="id_mileage">
  </div>

  <div class="input-group mb-1">
    <label class="input-group-text col-2" for="id_price">Описание:</label>
    <textarea class="form-control col-10" name="description" cols="40" rows="10" required id="id_description"
              aria-label="Описание"></textarea>
  </div>

  <label for="id_show_to">Кому показывать:</label>
  <select class="input-group mb-1" name="show_to" id="id_show_to" multiple>
    {% for usr in form.show_to.field.queryset %}
    <option value="{{ usr.id }}">{{ usr.username }}</option>
    {% endfor %}
  </select>

  <input class="btn btn-primary btn-block" type="submit" value="Добавить">
</form>
{% endblock %}

templates/assortment/add_user.html
{% extends 'assortment/base.html' %}
{% block content %}

<style>
.form-add-user {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-add-user .form-add-user-heading,
.form-add-user .checkbox {
  margin-bottom: 10px;
}
.form-add-user-heading {
  margin-top: 30px;
}
.form-add-user .checkbox {
  font-weight: normal;
}
.form-add-user .form-control {
  position: relative;
  height: auto;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
  padding: 10px;
  font-size: 16px;
}
.form-add-user .form-control:focus {
  z-index: 2;
}




</style>

<form class="form-add-user" enctype="multipart/form-data" method="post">
  {% csrf_token %}
  <input class="form-control {% if form.username.errors %} is-invalid {% endif %}" type="text" name="username"
         maxlength="150" required id="id_username" placeholder="Username">
  <div class="invalid-feedback">
    {% for error in form.username.errors %}
    <p>{{ error }}</p>
    {% endfor %}
  </div>
  <input class="form-control {% if form.password.errors %} is-invalid {% endif %}" type="password" name="password"
         maxlength="128" required id="id_password" placeholder="Password">
  <div class="invalid-feedback">
    {% for error in form.password.errors %}
    <p>{{ error }}</p>
    {% endfor %}
  </div>
  <input class="form-control {% if form.email.errors %} is-invalid {% endif %}" type="email" name="email"
         maxlength="254" required id="id_email" placeholder="Email">
  <div class="invalid-feedback">
    {% for error in form.email.errors %}
    <p>{{ error }}</p>
    {% endfor %}
  </div>
  <input class="form-control" type="text" name="first_name" required maxlength="150" id="id_first_name" placeholder="Имя">
  <input class="form-control" type="text" name="last_name" required maxlength="150" id="id_last_name" placeholder="Фамилия">
  <div class="form-check">
    <input class="form-check-input" type="checkbox" name="is_staff" id="id_is_staff">
    <label class="form-check-label" for="id_is_staff">Мотоподборщик</label>
  </div>
  <input class="btn btn-lg btn-primary btn-block" type="submit" value="Добавить">
</form>
{% endblock %}

templates/assortment/base.html
<!DOCTYPE html>
<html>
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
  <link rel="icon" href="/media/favicon.ico">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="/media/js/index.js"></script>
</head>
<style>
  body {
  background-color: #eee;
}
</style>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/motorcycles">Мотоциклы</a>
      </li>
      {% if user.is_staff %}
      <li class="nav-item">
        <a class="nav-link" href="/add_moto">Добавить мот</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/add_manufacturer">Добавить производителя</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/add_model">Добавить модель</a>
      </li>
      {% endif %}
      {% if user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link" href="/add_user">Добавить пользователя</a>
      </li>
      {% endif %}
    </ul>
  </div>
  </div class="collapse navbar-collapse">
  <ul class="navbar-nav ml-auto">
    {% if user.is_authenticated %}
    <label class="navbar-brand">{{ user.username }}</label>
    <li class="nav-item">
      <a class="nav-item nav-link" href="/logout">Logout</a>
    </li>
    {% else %}
    <li class="nav-item">
      <a class="nav-item nav-link" href="/login">Login</a>
    </li>
    {% endif %}
  </ul>

  </div>
</nav>
<div class="container-fluid mt-3">
  {% bootstrap_messages %}
  {% block content %}
  No content.
  {% endblock %}
</div>
</body>
</html>

templates/assortment/delete_confirm.html
{% extends 'assortment/base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
  <h3 class="text-center">Уверен, что хочешь удалить "{{ object }}"?</h3>
  <div class="text-center">
    <input class="btn btn-danger" type="submit" value="Удалить">
  </div>
</form>
{% endblock %}

templates/assortment/index.html
{% extends 'assortment/base.html' %}
{% block content %}
Типа главная страница
{% endblock %}

templates/assortment/login.html
{% extends 'assortment/base.html' %}
{% block content %}
<style>
.form-signin {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin .form-signin-heading,
.form-signin .checkbox {
  margin-bottom: 10px;
}
.form-signin-heading {
  margin-top: 30px;
}
.form-signin .checkbox {
  font-weight: normal;
}
.form-signin .form-control {
  position: relative;
  height: auto;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="text"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}



</style>
<div class="container">
  <form class="form-signin" method="post">
    {% csrf_token %}
    <h2 class="form-signin-heading">Please sign in</h2>
    <input type="text" name="username" autocapitalize="none" autocomplete="username" maxlength="150" id="id_username"
           class="form-control {% if form.username.errors %} is-invalid {% endif %}" placeholder="User Name" required
           autofocus>
    <input type="password" id="id_password" class="form-control {% if form.password.errors %} is-invalid {% endif %}"
           placeholder="Password" name="password" autocomplete="current-password" required>
    <div class="invalid-feedback">
      {% for error in form.username.errors %}
      <p>{{ error }}</p>
      {% endfor %}
      {% for error in form.password.errors %}
      <p>{{ error }}</p>
      {% endfor %}
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  </form>
</div>
{% endblock %}

templates/assortment/logout.html
{% extends 'assortment/base.html' %}
{% block content %}
Log out successful!
{% endblock %}

templates/assortment/motorcycle_list.html
{% extends 'assortment/base.html' %}
{% block content %}
<style>
  .text-left {
  text-align: left !important;
}
</style>
{% if motorcycle_list.count != 0 %}
  {% for motorcycle in motorcycle_list %}
    <div class="container-fluid btn-group btn-block" role="group">
        {% if motorcycle.pub_user == user or user.is_superuser %}
        <a href="/motorcycle/{{ motorcycle.id }}/" class="btn btn-light col-11 text-left">{{ motorcycle.model }} : {{ motorcycle.name }}</a>
        <a href="/delete_moto/{{ motorcycle.id }}/" class="btn btn-danger col-1">Удалить</a>
        {% else %}
        <a href="/motorcycle/{{ motorcycle.id }}/" class="btn btn-light text-left">{{ motorcycle.model }} : {{ motorcycle.name }}</a>
        {% endif %}
    </div>
  {% endfor %}
{% else %}
В данный момент нет доступных Вам мотоциклов.
{% endif %}
{% endblock %}

templates/assortment/universal_form.html
{% extends 'assortment/base.html' %}
{% load bootstrap4 %}
{% block content %}
<style>
.form-add-model {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
</style>
<form class="form-add-motorcycle" enctype="multipart/form-data" method="post">
  {% csrf_token %}
{% bootstrap_form form %}
  <input class="btn btn-primary btn-block" type="submit" value="Сохранить">
</form>
{% endblock %}